name: Release Please

on:
  push:
    branches:
      - main

permissions:
  issues: read
  contents: write
  pull-requests: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: python

      - name: Checkout
        if: ${{ steps.release.outputs.pr }}
        uses: actions/checkout@v4

      - name: Enable auto-merge for Release PR
        if: ${{ steps.release.outputs.pr }}
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ fromJson(steps.release.outputs.pr).number }}