name: Test

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     -master

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Lint
        run: hatch run style:check
      - name: Test
        id: test
        run: hatch run test-report
      - name: Upload pytest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: coverage.xml
