name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Lint
        run: hatch run style:check

      - name: Test
        id: test
        run: hatch run test-report
      - name: Upload pytest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
      - name: Publish pytest test results to PR
        if: always() && github.event_name == 'pull_request'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: junit/test-results.xml

      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: coverage.xml
      - name: Generate markdown summary of coverage
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          output: both
      - name: Publish coverage report to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && github.event_name == 'pull_request'
        with:
          header: Code Coverage
          recreate: true
          path: code-coverage-results.md