name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Lint
        run: hatch run style:check
      - name: Test
        id: test
        run: hatch run test-cov-html
      - name: Store coverage files
        if: success() || steps.test.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ./htmlcov
